### ISSUE TITLE
[UglifyJS] Unexpected token operator «=», expected punc «,»

### ISSUE THREAD

**Issue by tim-soft** [mattunt/hash-color-material#1]
Building for production yields this error: 
`Unexpected token operator «=», expected punc «,» [./node_modules/hash-color-material/index.js:6,0]`

https://github.com/matthiasunt/hash-color-material/blob/d4ed99cf3d882036ab698d9ff1050cb60801db09/index.js#L6

**Comment by matthiasunt** [comment]
Hi, sorry for that! Should be fixed now.
